apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caller-service
  template:
    metadata:
      labels:
        app: caller-service
    spec:
      containers:
        - name: caller-service
          image: localhost:5000/caller-service
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: caller-service
spec:
  selector:
    app: caller-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
